version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOMAIN=https://vaultwarden.nwdesigns.it
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=admin@nwdesigns.it
      - SMTP_FROM=admin@nwdesigns.it
      - SMTP_FROM_NAME=Vaultwarden
    volumes:
      - ./data:/data
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.nwdesigns.it`)"
      - "traefik.http.routers.vaultwarden.entrypoints=web"
      - "traefik.http.routers.vaultwarden.middlewares=crowdsec-bouncer@docker"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
